# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'SwiftHTML' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for SwiftHTML
  pod 'SnapKit'
  pod 'CocoaHTTPServer', :modular_headers => true

  target 'SwiftHTMLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftHTMLUITests' do
    # Pods for testing
  end

end
