# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'
# use_frameworks! :linkage => :static

target 'SwiftHTML' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for SwiftHTML
  pod 'SnapKit', :modular_headers => true
  pod 'CocoaHTTPServer', :modular_headers => true
  pod 'JXPhotoBrowser', '~> 3.0'
  pod 'Toast-Swift', '~> 5.0.1'

  target 'SwiftHTMLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftHTMLUITests' do
    # Pods for testing
  end

end
